// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FYGr9URrU2GuZboBCY1gGyOXbJLt6RQ',
    appId: '1:909954943991:web:a9a5633ef466ff05d23cf2',
    messagingSenderId: '909954943991',
    projectId: 'campus-cart-68fb5',
    authDomain: 'campus-cart-68fb5.firebaseapp.com',
    storageBucket: 'campus-cart-68fb5.firebasestorage.app',
    measurementId: 'G-007Z2W2DBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQ9rcFBbekFHlEwz1pN20daz0OpEtUOg',
    appId: '1:909954943991:android:39e5ec529e68cf68d23cf2',
    messagingSenderId: '909954943991',
    projectId: 'campus-cart-68fb5',
    storageBucket: 'campus-cart-68fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqjvVwuejmJCnpe9vRVnWWBVt85SjrTY',
    appId: '1:909954943991:ios:733185871b77c8b7d23cf2',
    messagingSenderId: '909954943991',
    projectId: 'campus-cart-68fb5',
    storageBucket: 'campus-cart-68fb5.firebasestorage.app',
    iosClientId: '909954943991-ci4kn3m3nra3abokam6s46hgbjdglhu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.madpractical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqjvVwuejmJCnpe9vRVnWWBVt85SjrTY',
    appId: '1:909954943991:ios:733185871b77c8b7d23cf2',
    messagingSenderId: '909954943991',
    projectId: 'campus-cart-68fb5',
    storageBucket: 'campus-cart-68fb5.firebasestorage.app',
    iosClientId: '909954943991-ci4kn3m3nra3abokam6s46hgbjdglhu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.madpractical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FYGr9URrU2GuZboBCY1gGyOXbJLt6RQ',
    appId: '1:909954943991:web:d33559ca716d928ad23cf2',
    messagingSenderId: '909954943991',
    projectId: 'campus-cart-68fb5',
    authDomain: 'campus-cart-68fb5.firebaseapp.com',
    storageBucket: 'campus-cart-68fb5.firebasestorage.app',
    measurementId: 'G-VM66RQQQ8M',
  );

}